### ISSUE TITLE
Sequence Masking

### ISSUE THREAD

**Issue by calclavia** [lucidrains/sinkhorn-transformer#1]
Often in training we need to mask out pad tokens within the attention module. Is there a plan to add support for this?

**Comment by lucidrains** [comment]
@calclavia Hi Henry! That's #3 on my todo list! It's tricky because I have to account for reordering with the sorting matrix. Feel free to keep this open until it is resolved

**Comment by lucidrains** [comment]
@calclavia I think it's done! You can try it by passing in your mask as the `input_mask` keyword

**Comment by calclavia** [comment]
Thanks!
