### ISSUE TITLE
axial positional embedding

### ISSUE THREAD

**Issue by rouniuyizu** [lucidrains/sinkhorn-transformer#13]
Hi, I noticed your implementation of so called "AxialPositionalEncoding" and am keen to understand further about it. Somehow I cannot find this trick mentioned in the original reformer/sinkhorn paper (I could have missed)... Would you pls enlighten me where it's rooted from? Thank you,

**Comment by lucidrains** [comment]
@rouniuyizu A fellow researcher friend actually told me about it when I was trying to perfect my Reformer implementation, and I found the results really compelling so I have added it to this repository as well. I believe people have been using this kind of positional embedding for a while, but you can find a more detailed description of the rationale behind the technique in this paper here https://openreview.net/pdf?id=H1e5GJBtDr

**Comment by rouniuyizu** [comment]
Thank you!
