### ISSUE TITLE
Size mismatch error when loading saved weights

### ISSUE THREAD

**Issue by epetros** [lucidrains/sinkhorn-transformer#20]
Greetings,
I used to save and load weights and optimizer for continue training with no problem, but today am facing the following error when trying to load:

RuntimeError: Error(s) in loading state_dict for AutoregressiveWrapper:
	size mismatch for net.net.sinkhorn_transformer.fn.layers.blocks.0.f.net.fn.sinkhorn_attention.sort_net.linear: copying a param with shape torch.Size([1, 4, 128, 33]) from checkpoint, the shape in current model is torch.Size([1, 4, 128, 34]).

Was there any change in the AutoregressiveWrapper?
Thanks

**Comment by lucidrains** [comment]
Oh no, yeah, there had been architecture changes in the recent version update. Did you upgrade to the latest version? You may have to downgrade back to what you had before

**Comment by epetros** [comment]
Ok, thanks.
