### ISSUE TITLE
Positional Embedding

### ISSUE THREAD

**Issue by ilya16** [lucidrains/sinkhorn-transformer#23]
Hi! Found out that `SinkhornTransformerLM` uses two positional encodings simultaneously:

https://github.com/lucidrains/sinkhorn-transformer/blob/2b65e24085562a4e308251398007e2ca9b86d7cc/sinkhorn_transformer/sinkhorn_transformer.py#L778-L779

https://github.com/lucidrains/sinkhorn-transformer/blob/2b65e24085562a4e308251398007e2ca9b86d7cc/sinkhorn_transformer/sinkhorn_transformer.py#L792-L793

I guess `pos_emb` can be removed as it introduces memory overhead and makes useless the utilization of Axial Positional Encoding that is designed to reduce the number of positional encoding parameters.

Is there a special reasoning behind that?

**Comment by lucidrains** [comment]
@ilya16 I had originally added the axial positional embedding because the attention sorting network functioned best with it as opposed to only with absolute. You are right, I believe axial is good enough that the absolute pos embedding won't be needed at all, I'll remove it!

**Comment by lucidrains** [comment]
@ilya16  done!

**Comment by lucidrains** [comment]
@ilya16 how has this variant of attention work out for your projects?

**Comment by ilya16** [comment]
@lucidrains you are welcome!

About the model. Sinkhorn Transformer converges faster than Reformer to similar results. Right now I am also playing around with your other Transformer implementations :D
