### ISSUE TITLE
Error with Autopadder 

### ISSUE THREAD

**Issue by soonchangAI** [lucidrains/sinkhorn-transformer#28]
Hi, I am facing a problem 
import torch
from sinkhorn_transformer import SinkhornTransformer, Autopadder

model = Autopadder(SinkhornTransformer(
    dim = 64,
    heads = 1,
    depth = 1,
    bucket_size = 128))

x = torch.randn(10, 789, 64)
y = model(x) 
print(y.shape)

Output Error : RuntimeError: shape '[10, 7, -1, 171]' is invalid for input of size 1349190

**Comment by lucidrains** [comment]
@soon22 Hi Soon! Sorry for the late response, but I believe I have fixed this in https://github.com/lucidrains/sinkhorn-transformer/releases/tag/0.11.4

**Comment by soonchangAI** [comment]
Thank you ! It works
