### ISSUE TITLE
Post pre-trained models please

### ISSUE THREAD

**Issue by Hellisotherpeople** [lucidrains/sinkhorn-transformer#3]
Doing so might make your # of github stars go up 10-100x if it's actually competitive with current models.

**Comment by lucidrains** [comment]
@Hellisotherpeople Hi Allen! Despite having some unexpected publicity, I want to let you know this is still exploratory work lol. I do not really care about stars, just that I am fully sure I can make it perform as well and as flexibly as a plain vanilla transformer. Early results seem promising, so stay tuned!
